app:
    resource: "@AppBundle/Controller/"
    type:     annotation

home:
    pattern:      /
    defaults:  { _controller: AppBundle:Default:index }

gallery:
    pattern:      /gallery
    defaults:  { _controller: AppBundle:Gallery:index }

mars:
    pattern:      /mars
    defaults:  { _controller: AppBundle:Mars:index }

menu:
    pattern:      /menu/get
    defaults:  { _controller: AppBundle:Menu:index }
